#!/bin/bash
#
# Cmake wrapper
#
# Copyright (C) 2011,2013 Philip Muskovac <yofel@gmx.net>
# Copyright (C) 2015 RJVB <rjvbertin@gmail.com>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 
# 1. Redistributions of source code must retain the copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. The name of the author may not be used to endorse or promote products 
#    derived from this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
###############################################################################

if [ -z "$MPENV" ]; then
    echo "### FATAL: MPENV undefined"
    echo "### You are not in a MacPorts build environment."
    echo "### Please run 'mp-env' before running mp-cmake"
    exit 1
fi

cmakeopts="-DCMAKE_INSTALL_PREFIX=$MPDIR \
           -DCMAKE_PREFIX_PATH=$MPDIR \
           -DCMAKE_BUILD_TYPE=MacPorts"

[ -e ~/.mprc ] && . ~/.mprc

if [ -z "$MP_CMAKE_OVERRIDE" ]; then
    $MPDIR/bin/cmake $cmakeopts $MP_CMAKE_OPTS $@
else
    $MPDIR/bin/cmake $MP_CMAKE_OVERRIDE $@
fi
