#!/bin/bash
#
# Build environment setup script
#
# Copyright (C) 2011,2013 Philip Muskovac <yofel@gmx.net>
# Copyright (C) 2015 RJVB <rjvbertin@gmail.com>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 
# 1. Redistributions of source code must retain the copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. The name of the author may not be used to endorse or promote products 
#    derived from this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
###############################################################################

if [ -z $MPENV ]; then
    export MPENV=1
    . @PREFIX@/etc/build_environment.rc

    if [ -z "$MP_SESSION" ]; then
        if [ -e $MPDIR/bin/kbuildsycoca5 ]; then
            kbuildsycoca5
        fi
    fi

    echo "### WARNING: This shell is now set up as a MacPorts build environment"
    echo "### It is strongly advised to exit this shell before running any"
    echo "### GUI application not belonging to MacPorts!"
    echo 

    if [[ "$SHELL" == '/bin/bash' ]]; then
        exec bash --rcfile $MPDIR/etc/bashrc
    else
        exec $SHELL
    fi

else
    echo "FATAL: running a nested MacPorts shell isn't supported!"
    echo "### Your are already running a MacPorts shell, if you want to restart it"
    echo "### please exit and run this script again!"
    echo 
    exit 1
fi
